<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RI9GKG4" failures="2" tests="14" name="MEMTest" time="72.902" errors="0" timestamp="2024-02-26T19:14:43 IST">
  <testcase classname="mem.qa.testScripts.LoginPage1Test" name="checkTitleTest" time="0.105"/>
  <testcase classname="mem.qa.testScripts.LoginPage1Test" name="checkLoginTest" time="21.267"/>
  <testcase classname="mem.qa.testScripts.LoginPage1Test" name="checkselectStore" time="12.259"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkPageTitleTest" time="4.57"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkPageHeadingTest" time="0.052"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopNameTest" time="0.053"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopURLTest" time="0.057"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopEmailTest" time="0.057"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkShopifyPlanTest" time="0.059"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSignOutBtnTest" time="0.074"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkTitleGlobalPricinTest" time="0.24"/>
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSaveBtnTest" time="3.369">
    <failure type="java.lang.AssertionError" message="expected [Pricing updated successfully] but found [Something went wrong while updating the pricing rules]">
      <![CDATA[java.lang.AssertionError: expected [Pricing updated successfully] but found [Something went wrong while updating the pricing rules]
at mem.qa.testScripts.MemSettingPageTest.checkSaveBtnTest(MemSettingPageTest.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSaveBtnTest -->
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkSaveAndUpdateTest" time="1.372">
    <failure type="java.lang.AssertionError" message="expected [Pricing rules update in progress.] but found [Something went wrong while updating the pricing rules]">
      <![CDATA[java.lang.AssertionError: expected [Pricing rules update in progress.] but found [Something went wrong while updating the pricing rules]
at mem.qa.testScripts.MemSettingPageTest.checkSaveAndUpdateTest(MemSettingPageTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSaveAndUpdateTest -->
  <testcase classname="mem.qa.testScripts.MemSettingPageTest" name="checkVisibilityBtnTest" time="5.721"/>
</testsuite> <!-- MEMTest -->
